### ISSUE TITLE
Не загружается плагин addon.js 

### ISSUE THREAD

**Issue by Semulia** [scabrum/plugins#2]
Плагин добавляется в Lampa, имеет статус 200, но при загрузке выдаётся ошибку что невозможно загрузить плагин. Соответсвенно пункт в меню «Плагины» не появляется. Проблема появилась недавно. Ещё две недели назад все работало как часики.

**Comment by Serega007RU** [comment]
Автор Lampa заблокировал этот репозиторий, добавил в чёрный список, поэтому плагины и перестали работать https://github.com/yumata/lampa-source/commit/1b884444e57afc0782613720a6c3e3f7ed2bb6de

**Comment by scabrum** [comment]
Closed
